name: "Setup cargo"
description: Restore cargo cache and install dependencies

runs:
  using: "composite"
  steps:
    - name: Restore cargo cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: Install dependencies
      run: |
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
        cargo update
      shell: bash
