name: Validate Code
on:
  push:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-code-validation:
    name: Rust validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Restore cargo cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Install dependencies
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
          cargo update
      - name: Validate code
        run: |
          cargo check --quiet
      - name: Validate linters
        run: |
          ./configs/scripts/cargo-fmt.sh
          cargo clippy --all-features --all-targets --quiet
      - name: Validate tests
        run: |
          echo "Unimplemented yet..."
